name: Upload Archives
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_Access_Key }}
          aws-secret-access-key: ${{ secrets.AWS_Access_Secret }}
          aws-region: us-east-1

      - name: Uploading from /home folder
        run: aws s3 sync ./src/portais/home s3://${{ secrets.AWS_Bucket_Name }}/portais/home --size-only

      - name: Uploading from /maquininha folder
        run: aws s3 sync ./src/portais/maquininha s3://${{ secrets.AWS_Bucket_Name }}/portais/maquininha --size-only

      - name: Sync files to Github
        run: aws s3 sync s3://${{ secrets.AWS_Bucket_Name }} ./
